### ISSUE TITLE
Memastikan fungsi backup dan replication sistem aplikasi dan pangkalan data server EID berjalan dengan baik.

### ISSUE THREAD

**Issue by abigoroth** [abigoroth/mbop#1]
sekarang ni dia pakai VM ke macam mana?

**Comment by killkaze** [comment]
vm citrix

**Comment by abigoroth** [comment]
@killkaze kita backup VM dia seketul ke cane? 😄

**Comment by killkaze** [comment]
4 physical server. Each server host vm citrix. ada +- 7 guest debian os dalam satu host vm.

Backup taktau kita ada buat? kena tanya zul. 

So far backup diorang dah ada:

1. app backup pakai tar dan mysql backup mysqldump dan transfer to server 1 (backup server)
2. Ni tak pasti cara apa diorang pakai tapi backup ke another backup server

**Comment by abigoroth** [comment]
@killkaze kalau backup vm seketul senang, sebab mesti ada attachment file dan lain-lain kan?

**Comment by zulcht** [comment]
buat backup task termasuk dlm scope

**Comment by zulcht** [comment]
sorry..tak masuk dlm scope..typo

**Comment by abigoroth** [comment]
ooo, kena test kut backup dia jalan ka dak kan ? @zulcht

**Comment by zulcht** [comment]
actually dlm scope tak mentioned pun pasal backup..so tak perlu test unless they request la..plus, backup server dorg skang tgh powered-off (maintenance mode) @obigoroth

**Comment by abigoroth** [comment]
![Pasted_Image_19_07_2019__6_35_PM](https://user-images.githubusercontent.com/520990/61529470-f8853e00-aa53-11e9-9f50-0c8680b5c31a.png)

@zulcht @imankraf666

**Comment by imankraf666** [comment]
betul buat backup task takde dalam skop. kita hanya perlu monitor sahaja
